-- LEER REGISTROS USANDO CONDICIONALES

SELECT * FROM ejemplo_tabla WHERE edad  = 89; -- SELECCIONA UN DONDE SE CUMPLA LA CONDICION PUESTA EN EL WHERE

SELECT * FROM ejemplo_tabla WHERE nombre IN("Edwin", 'Braily'); -- TRAER MULTIPLES REGISTROS EN ESPECIFICO

SELECT * FROM ejemplo_tabla WHERE apellido  LIKE 'r%'; -- TRAER REGISTROS QUE COMIENCEN CON X PARAMETRO, % SE USA PARA IGNORAR EL RESTO DE DATOS

SELECT * FROM ejemplo_tabla WHERE apellido  LIKE '%o'; -- TRAER REGISTROS QUE TERMINEN CON X PARAMETRO, % SE USA PARA IGNORAR EL RESTO DE DATOS

SELECT * FROM ejemplo_tabla WHERE nombre  LIKE '%i%'; -- TRAER REGISTROS QUE CONTENGAN X PARAMETRO, % SE USA PARA IGNORAR EL RESTO DE DATOS

SELECT * FROM ejemplo_tabla WHERE nombre  NOT LIKE '%i%'; -- ES LO CONTRARIO A LIKE, CON ESTO NO TRAEMOS LOS REGISTROS QUE CONTENGAN "i"


-- USO DE OPERADORES RELACIONALES USANDO SELECT

SELECT * FROM ejemplo_tabla WHERE edad != 89; -- SE PUEDE USAR <> EN LUGAR DE !=

SELECT * FROM ejemplo_tabla WHERE edad > 0; -- TRAER EDADES QUE SEAN MAYORES QUE CERO

SELECT * FROM ejemplo_tabla WHERE edad <=89 ; -- TRAER EDADES QUE SEAN MENORES O IGUAL A 89

-- USO DE OPERADORES LOGICOS USANDO SELECT

SELECT * FROM ejemplo_tabla WHERE NOT nombre = 'Jerlinson'; -- TRAER TODOS LOS REGISTROS EN DONDE EL NOMBRE NO SEA JERLINSON

SELECT * FROM ejemplo_tabla WHERE nombre = 'Jerlinson' AND edad >= 89; -- RETORNA UN REGISTRO QUE CUMPLA CON LAS DOS CONDICIONES

SELECT * FROM ejemplo_tabla WHERE nombre = 'Jerlinson' AND edad >= 89 AND apellido  = 'Gomez'; -- RETORNA UN REGISTRO QUE CUMPLA CON LAS TRES CONDICIONES

SELECT * FROM ejemplo_tabla WHERE nombre = 'Jerlinson' OR edad = 85; -- RETORNA UN REGISTRO QUE CUMPLA CON ALMENOS UNA DE LAS DOS CONDICIONES
