-- EL COMANDO CREATE, SIRVE PARA CREAR TABLAS O BASES DE DATOS, ETC...

CREATE DATABASE nombre_ejemplo;

-- EL COMANDO DROP, SIRVE PARA BORRAR TABLAS O BASES DE DATOS, ETC...

DROP DATABASE nombre_ejemplo;